# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TyphoonRestClientDemoSwift' do
    pod 'TyphoonRestClient'
end

target 'TyphoonRestClientDemoSwiftTests' do

end

